version: 2.1
orbs:
  go: circleci/go@1.2.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'

    steps:
      - checkout
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: mkdir -p /tmp/test-results
      - run:
          name: Run unit tests
          command: |
            gotestsum --junitfile /tmp/test-results/unit-tests.xml
      - run: go build ./...
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-reports
